name: Check Slots

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      date:
        description: "Date du créneau à vérifier (format AAAA-MM-JJ)"
        required: true
        default: "2024-11-21"

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Vérifier uniquement les fichiers nécessaires
      - name: Checkout necessary files
        uses: actions/checkout@v3
        with:
          # Fetch minimal history
          fetch-depth: 1
          # Optional: Include only specific paths (uncomment if applicable)
          # path: |
          #   Creneaux.py
          #   config.env

      # Étape 2 : Installer Python uniquement
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Étape 3 : Installer uniquement la dépendance requise
      - name: Install requests library
        run: python -m pip install --quiet requests

      # Étape 4 : Charger les variables et vérifier si DATE est défini
      - name: Load variables from file and check DATE
        id: load-vars
        run: |
          # Charger le fichier config.env si présent
          if [ -f config.env ]; then
            source config.env
          else
            echo "Error: config.env file not found!"
            exit 1
          fi

          # Vérifier si DATE est vide
          if [ -z "$DATE" ]; then
            echo "DATE is empty. Skipping script execution."
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "DATE is set to: $DATE"
            echo "DATE=$DATE" >> $GITHUB_ENV
            echo "continue=true" >> $GITHUB_ENV
          fi

      # Étape 5 : Exécuter le script si DATE est valide
      - name: Run Python script
        if: env.continue == 'true'
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
        run: python Creneaux.py $DATE
