name: Check Slots

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      date:
        description: "Date du créneau à vérifier (format AAAA-MM-JJ)"
        required: true
        default: "2024-11-21"

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # Ensure latest version of checkout action

      - name: Setup Python
        uses: actions/setup-python@v4 # Ensure latest version of setup-python action
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Load variables from file
        id: load-vars
        run: |
          # Load variables from config.env
          if [ -f config.env ]; then
            source config.env
          else
            echo "Error: config.env file not found!"
            exit 1
          fi

          # Check if DATE is empty
          if [ -z "$DATE" ]; then
            echo "DATE is empty. Skipping script execution."
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "DATE is set to: $DATE"
            echo "DATE=$DATE" >> $GITHUB_ENV
            echo "continue=true" >> $GITHUB_ENV
          fi

      - name: Run script
        if: env.continue == 'true'
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
        run: |
          echo "Executing script with DATE: $DATE"
          python Creneaux.py $DATE

      - name: Skip message
        if: env.continue == 'false'
        run: |
          echo "The script was not executed because DATE is not set."
