name: Check Slots

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install requests

      - name: Inspect Pushover secrets (longueur uniquement)
        run: |
          echo "PUSHOVER_USER_KEY len: ${#PUSHOVER_USER_KEY}"
          echo "PUSHOVER_API_TOKEN len: ${#PUSHOVER_API_TOKEN}"
          [[ ${#PUSHOVER_USER_KEY} -eq 30 ]] || exit 1
          [[ ${#PUSHOVER_API_TOKEN} -eq 30 ]] || exit 1
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}

      - name: Run script
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
        run: |
          echo "Executing script"
          python Creneaux.py
